main_metric : 'T5_A'

eval:
  freq : 1
  data :
    name : 'EGTEA_GAZE+'
    split : 'valid1'
    
    feat_file : './data/feature/EGTEA_SP1_RGB_TSN/'    
    feature : 'TSN'
    feature_fps : 30
    feature_dim : 1024

    forward_frame : 8
    past_frame : 20
    fps : 4
    batch_size : 512
    num_workers : 2
    cache : false

  
train:
  data:
    name : 'EGTEA_GAZE+'
    split : 'train1'

    feat_file : './data/feature/EGTEA_SP1_RGB_TSN/'    
    feature : 'TSN'
    feature_fps : 30
    feature_dim : 1024

    forward_frame : 8
    past_frame : 20

    fps : 4
    batch_size : 512
    num_workers : 2
    cache : False

  optimizer:
    name: 'AdamW'
    base_lr : 5e-5
    betas : (0.9, 0.999)
    weight_decay : 1e-5
  
  max_epoch : 100
  scheduler:
    name : 'WarmupCos'
    warmup_epoch : 5
    step : [100]


curriculum:
  gamma_min : 0.95
  gamma_max : 1.
  
  
model:
  name : 'DCR'
  
  feat_dim: 1024
  past_frame : 20
  anticipation_frame : 4
  action_frame : 4
  
  reasoner:
    name : 'transformer'
    d_model : 1024
    nhead : 16
    dff : 4096
    depth : 6
    dropout : 0.1
    pe_type : 'learnable'

  classifier:
    dropout: 0.4
    action: true

  loss:
    name : 'CE'
    feat_mse : 2.5
    next_cls : 1.

    smooth: 0.6