main_metric : 'All_A'

eval:
  freq : 1
  data :
    name : 'EPIC-KITCHENS-100'
    split : 'valid'

    feat_file : './data/feature/EK100_RGB_TSN/'
    feature : 'TSN'
    feature_fps : 30
    feature_dim : 1024
    
    forward_frame : 8
    past_frame : 40

    fps : 4
    batch_size : 128
    num_workers : 2
    cache : false


model:
  name : 'DCR'
  
  feat_dim: 1024
  past_frame : 40
  anticipation_frame : 4
  action_frame : 4
  
  reasoner:
    name : 'transformer'
    d_model : 1024
    nhead : 16
    dff : 4096
    depth : 6
    dropout : 0.1
    pe_type : 'learnable'
  
  classifier:
    dropout: 0.4
    action: true
    verb: true
    noun : true

  loss:
    name : 'CE'
    feat_mse : 2.
    next_cls : .5
    smooth: 0.2