main_metric : 'All_A'

eval:
  freq : 1
  
  data :
    name : 'EPIC-KITCHENS-100'
    split : 'valid'

    feat_file : './data/feature/EK100_RGB_TSM/'
    feature : 'TSM'
    feature_fps : 8
    feature_dim : 2048

    forward_frame : 8
    past_frame : 40

    fps : 4
    batch_size : 128
    num_workers : 2
    cache : False
  
  
model:
  name : 'DCR'
  
  feat_dim: 2048
  past_frame : 40
  anticipation_frame : 4
  action_frame : 4
  
  reasoner:
    name : 'transformer'
    d_model : 1024
    nhead : 16
    dff : 4096
    depth : 6
    dropout : 0.1
    pe_type : 'learnable'

  classifier:
    dropout: 0.4
    action: true
    verb: true
    noun : true
