
main_metric : 'All_A'

eval:
  freq : 1
  data :
    name : 'EPIC-KITCHENS-100'
    split : 'valid'

    feat_file : './data/feature/EK100_FLOW_TSN/'
    feature : 'TSN'
    feature_fps : 30
    feature_dim : 1024

    forward_frame : 8
    past_frame : 40

    fps : 4
    batch_size : 512
    num_workers : 2
    cache : false

train:
  data :
    name : 'EPIC-KITCHENS-100'
    split : 'valid'

    feat_file : './data/feature/EK100_FLOW_TSN/'
    feature : 'TSN'
    feature_fps : 30
    feature_dim : 1024

    forward_frame : 8
    past_frame : 40

    fps : 4
    batch_size : 512
    num_workers : 2
    cache : false

  optimizer:
    name: 'SGD'
    base_lr : 1e-2
    betas : (0.9, 0.999)
    weight_decay : 1e-5
  
  max_epoch : 100
  scheduler:
    name : 'WarmupCos'
    warmup_epoch : 5
    step : [100]



curriculum:
  gamma_min : 0.95
  gamma_max : 1.


model:
  name : 'DCR'
  
  feat_dim: 1024
  past_frame : 40
  anticipation_frame : 4
  action_frame : 4
  
  reasoner:
    name : 'lstm'
    d_model : 1024
    depth : 1
    dropout : 0.1

  classifier:
    dropout: 0.4
    action: true
    verb: true
    noun : true

  loss:
    name : 'CE'
    verb : 1.
    noun : 1.
    feat_mse : 1.
    next_cls : 1.
    smooth: 0.2