main_metric : 'All_A'

eval:
  freq : 1
  data :
    name : 'EPIC-KITCHENS-100'
    split : 'valid'

    feat_file : './data/feature/EK100_OBJ_FRCNN/'
    feature : 'FRCNN'
    feature_fps : 30
    feature_dim : 352

    forward_frame : 8
    past_frame : 40
    fps : 4
    batch_size : 128
    num_workers : 4
    cache :  false


train:
  data:
    name : 'EPIC-KITCHENS-100'
    split : 'train'

    feat_file : './data/feature/EK100_OBJ_FRCNN/'
    feature : 'FRCNN'
    feature_fps : 30
    feature_dim : 352

    forward_frame : 8
    past_frame : 40
    fps : 4
    batch_size : 128
    num_workers : 4
    cache :  false
  optimizer:
    name: 'SGD'
    base_lr : 1e-2
    betas : (0.9, 0.999)
    weight_decay : 1e-5
  
  max_epoch : 100
  scheduler:
    name : 'WarmupCos'
    warmup_epoch : 5
    step : [100]


curriculum:
  gamma_min : 0.95
  gamma_max : 1.


model:
  name : 'DCR'
  
  feat_dim: 352
  past_frame : 40
  anticipation_frame : 4
  action_frame : 4
  
  reasoner:
    name : 'transformer'
    d_model : 1024
    nhead : 16
    dff : 4096
    depth : 6
    dropout : 0.1
    pe_type : 'learnable'

  classifier:
    dropout: 0.4
    action: true
    verb: true
    noun : true

  loss:
    name : 'CE'
    verb : .5
    noun : .5
    feat_mse : 1.
    next_cls : 1.
    smooth: 0.1